definition:
  openapi: 3.0.3
  info:
    description: >-
      EletroInfo :: Eletro Informática - Para assegurar a excelência dos nossos
      serviços, a Eletroinfo continua a explorar e adotar constantemente
      inovações tecnológicas, com o objetivo primordial de satisfazer plenamente
      os nossos clientes.
    version: 1.0.0
    title: API - Eletro Info
  tags:
    - name: Cálculo de Autonomia de Nobreak
      description: >-
        Calcula a autonomia de um nobreak com base no consumo, potência e tempo
        de operação, ajudando a determinar o modelo mais adequado para sua
        necessidade.
    - name: Viabilidade de Instalação de CFTV
      description: >-
        Analisa a viabilidade de instalação de sistemas de CFTV considerando
        fatores como área coberta, quantidade de câmeras e infraestrutura
        disponível.
    - name: Calculadora de IP (IPv4)
      description: >-
        Realiza cálculos de sub-redes IPv4, exibindo detalhes como máscara de
        rede, IP inicial e final, além da quantidade de hosts disponíveis.
    - name: Calculadora de IP (IPv6)
      description: >-
        Calcula sub-redes IPv6, gerando informações como prefixo de rede, IP
        inicial e final, e o total de endereços disponíveis na sub-rede.
    - name: Consulta de IP
      description: >-
        Fornece informações detalhadas sobre um endereço IP, como tipo
        (IPv4/IPv6), localização aproximada e provedor de internet.
    - name: Geolocalização de IP
      description: >-
        Localiza geograficamente um endereço IP, como tipo (IPv4/IPv6),
        fornecendo informações como país, cidade e provedor associado ao
        endereço.
    - name: Teste de Portas de Rede
      description: >-
        Verifica a disponibilidade ou bloqueio de portas específicas em uma
        rede, auxiliando no diagnóstico de problemas de conectividade.
    - name: Consulta Fabricante pelo Endereço MAC
      description: >-
        Identifica o fabricante de dispositivos a partir de endereços MAC, útil
        para diagnósticos e organização de redes.
    - name: Calculadora de Transferência de Dados
      description: >-
        Calcula o tempo necessário para transferir arquivos com base no tamanho
        e na velocidade da conexão, otimizando o planejamento de transferências.
    - name: Cálculo de Latência e Largura de Banda
      description: >-
        Avalia a performance da memória RAM calculando a latência e a largura de
        banda, fornecendo métricas detalhadas para otimização do sistema.
    - name: Calculadora de RAID
      description: >-
        A Calculadora de Capacidade RAID faz uma estimativa da utilização de
        armazenamento de várias configurações de unidades e níveis RAID.
    - name: Calculadora de Metabolismo Basal (TMB)
      description: >-
        Calcula o metabolismo basal de uma pessoa usando dados como idade, peso,
        altura e gênero, auxiliando no planejamento de dietas e treinos.
  servers:
    - url: https://tools.eletroinfo.site
      description: ''
  components:
    schemas:
      AutonomiaNobreakRequest:
        type: object
        properties:
          carga_aplicada:
            type: integer
            description: Consumo do equipamento em watts (W).
            example: 100
          tensao_bateria:
            type: integer
            description: Tensão nominal da bateria em volts (V).
            example: 12
          capacidade_bateria:
            type: integer
            description: Capacidade nominal da bateria em ampere-hora (Ah).
            example: 7
          quantidade_baterias:
            type: integer
            description: Quantidade de baterias no sistema.
            example: 2
          tipo_bateria:
            type: string
            description: Tipo da bateria.
            example: chumbo_acido
        required:
          - carga_aplicada
          - tensao_bateria
          - capacidade_bateria
          - quantidade_baterias
          - tipo_bateria
      ViabilidadeCFTVRequest:
        type: object
        properties:
          tensao_fonte:
            type: integer
            description: Tensão da fonte de alimentação em volts (V).
            example: 12
          bitola_cabo:
            type: integer
            description: Bitola do cabo em milímetros quadrados (mm²).
            example: 5
          distancia:
            type: integer
            description: Distância entre a fonte e a câmera em metros (m)
            example: 67
          tensao_camera:
            type: integer
            description: >-
              Tensão mínima necessária para o funcionamento da câmera em volts
              (V)
            example: 12
          corrente_camera:
            type: integer
            description: Corrente consumida pela câmera em amperes (A).
            example: 1
        required:
          - tensao_fonte
          - bitola_cabo
          - distancia
          - tensao_camera
          - corrente_camera
      CalculadoraIPv4Request:
        type: object
        properties:
          ipAddress:
            type: string
            description: Representa o endereço IP que será analisado.
            example: 192.168.100.1
          subnetMask:
            type: string
            description: >-
              Deve ser informado no formato CIDR (ex.: /22) (ex.:
              255.255.252.0).
            example: /22
      CalculadoraIPv6Request:
        type: object
        properties:
          ipAddress:
            type: string
            description: Representa o endereço IP que será analisado.
            example: 2a02:4780:14:5a20::1
          subnetMask:
            type: string
            description: 'Deve ser informado no formato CIDR (ex.: /64).'
            example: /64
      ConsultaIPRequest:
        type: object
        properties:
          ip:
            type: string
            description: >-
              Endereço IP que se deseja consultar (opcional). Se vazio, retorna
              informações sobre o IP público atual
            example: 200.221.11.100
      GeolocalizacaoIPRequest:
        type: object
        properties:
          ip:
            type: string
            description: Endereço IP que se deseja consultar.
            example: 200.221.11.100
      TestePortasRedeRequest:
        type: object
        properties:
          host:
            type: string
            description: O endereço IP ou hostname do servidor.
            example: google.com.br
          port:
            type: array
            description: A porta a ser testada.
            example:
              - 80
              - 443
              - 53
          timeout:
            type: integer
            description: Tempo limite em milissegundos para a conexão.
            example: 2000
      ConsultaFabricanteMACRequest:
        type: object
        properties:
          macaddress:
            type: string
            description: >-
              Endereço MAC que se deseja consultar, retorna informações sobre
              endereço MAC informado
            example: 00-1A-2B-3C-4D-5E
      CalculadoraDataTransferRequest:
        type: object
        properties:
          tamanho:
            type: integer
            description: Informe o tamanho total do arquivo que será transferido.
            example: 500
          unidadeTamanho:
            type: string
            description: >-
              Selecione a unidade de medida correspondente ao tamanho do arquivo
              (por exemplo, MB, GB, TB).
            example: GB
          velocidade:
            type: integer
            description: Digite a velocidade disponível para a transferência dos dados.
            example: 67
          unidadeVelocidade:
            type: string
            description: >-
              Selecione a unidade de medida da velocidade de transferência (por
              exemplo, Mbps, MB/s, Gbps).
            example: MB
        required:
          - tamanho
          - unidadeTamanho
          - velocidade
          - unidadeVelocidade
  paths:
    /api/AutonomiaNobreak:
      post:
        tags:
          - Cálculo de Autonomia de Nobreak
        summary: Cálculo de Autonomia de Nobreak
        description: >
          ## Entradas Necessárias

          Os seguintes parâmetros devem ser fornecidos no corpo da requisição:


          - **carga_aplicada:** Consumo do equipamento em watts (W).

          - **tensao_bateria:** Tensão nominal da bateria em volts (V).

          - **capacidade_bateria:** Capacidade nominal da bateria em ampere-hora
          (Ah).

          - **quantidade_baterias:** Quantidade de baterias no sistema.

          - **tipo_bateria:** Tipo da bateria (veja lista de valores válidos).


          ## Valores Válidos para o Campo `tipo_bateria`


          - `chumbo_acido` - Chumbo-Ácido (Lead-Acid)

          - `ion_litio` - Íon de Lítio (Li-ion)

          - `niquel_cadmio` - Níquel-Cádmio (NiCd)

          - `niquel_hidreto_metalico` - Níquel-Hidreto Metálico (NiMH)

          - `lithium_ferro_fosfato` - Lítio-Ferro-Fosfato (LiFePO4)

          - `lithium_polimero` - Lítio-Polímero (LiPo)

          - `zinco_ar` - Zinco-Ar (Zn-Air)

          - `niquel_ferro` - Níquel-Ferro (NiFe)

          - `sodio_enxofre` - Sódio-Enxofre (NaS)

          - `zinco_brometo` - Zinco-Brometo (ZnBr)

          - `magnesio` - Magnésio

          - `chumbo_carbono` - Chumbo-Carbono

          - `fluxo_redox` - Fluxo Redox

          - `aluminio_ar` - Alumínio-Ar (Al-Air)

          - `lithium_enxofre` - Lítio-Enxofre (Li-S)

          - `desconhecida` - Tipo de bateria desconhecido
        parameters: []
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutonomiaNobreakRequest'
        responses:
          '200':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: false
                    status: 200
                    result:
                      tensaocorte: 19.8
                      autonomia: '09:25:04'
                    message: Cálculo realizado com sucesso.
          '400':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: true
                    status: 400
                    result: null
                    message: >-
                      Todos os valores devem ser preenchidos: carga_aplicada,
                      tensao_bateria, capacidade_bateria, quantidade_baterias,
                      tipo_bateria. Por favor, corrija e tente novamente.
          '404':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    Status:
                      error: true
                      status: 404
                      result: null
                      message: >-
                        JSON enviado está incorreto. Por favor, revise o formato
                        e tente novamente.
          '500':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: true
                    status: 500
                    result: null
                    message: Erro ao calcular a autonomia.
    /api/ViabilidadeCFTV:
      post:
        tags:
          - Viabilidade de Instalação de CFTV
        summary: Viabilidade de Instalação de CFTV
        description: >
          ## Entradas Necessárias


          Os seguintes parâmetros devem ser fornecidos no corpo da requisição:


          - **tensao_fonte:** Tensão da fonte de alimentação em volts (V).

          - **bitola_cabo:** Bitola do cabo em milímetros quadrados (mm²).

          - **distancia:** Distância entre a fonte e a câmera em metros (m).

          - **tensao_camera:** Tensão mínima necessária para o funcionamento da
          câmera em volts (V).

          - **corrente_camera:** Corrente consumida pela câmera em amperes (A).


          ## Valores Válidos para o Campo `bitola_cabo`


          - `0` - 26AWG (0.14 mm²)

          - `1` - 24AWG (0.20 mm²)

          - `2` - 22AWG (0.33 mm²)

          - `3` - 20AWG (0.50 mm²)

          - `4` - 17AWG (1.00 mm²)

          - `5` - 15AWG (1.50 mm²)

          - `6` - 13AWG (2.50 mm²)

          - `7` - 11AWG (4.00 mm²)
        parameters: []
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViabilidadeCFTVRequest'
        responses:
          '200':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: false
                    status: 200
                    result:
                      resistencia_metro: '0.010'
                      resistencia_total: '1.34'
                      tensao_fornecida: '10.79'
                      distancia_maxima: '66.67'
                      viavel: false
                    message: Cálculo realizado com sucesso.
          '400':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: true
                    status: 400
                    result: null
                    message: >-
                      Todos os valores devem ser preenchidos: tensao_fonte,
                      bitola_cabo, distancia, tensao_camera, corrente_camera.
                      Por favor, corrija e tente novamente.
          '404':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    Status:
                      error: true
                      status: 404
                      result: null
                      message: >-
                        JSON enviado está incorreto. Por favor, revise o formato
                        e tente novamente.
          '500':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: true
                    status: 500
                    result: null
                    message: Erro ao calcular a viabilidade.
    /api/CalculadoraIPv4:
      post:
        tags:
          - Calculadora de IP (IPv4)
        summary: Calculadora de IP (IPv4)
        description: >
          ## Entradas Necessárias


          Os seguintes parâmetros devem ser enviados no corpo da requisição:


          - **ipAddress**: Representa o endereço IP que será analisado.

          - **subnetMask**: Deve ser informado no formato CIDR (ex.: /22) (ex.:
          255.255.252.0).


          # Valores Válidos para o Campo `subnetMask`


          Os valores de prefixo CIDR (`/n`) e suas correspondentes máscaras de
          rede (Network Mask) são os seguintes:


          - `/1` - 128.0.0.0

          - `/2` - 192.0.0.0

          - `/3` - 224.0.0.0

          - `/4` - 240.0.0.0

          - `/5` - 248.0.0.0

          - `/6` - 252.0.0.0

          - `/7` - 254.0.0.0


          ### Classe A


          - `/8` - 255.0.0.0

          - `/9` - 255.128.0.0

          - `/10` - 255.192.0.0

          - `/11` - 255.224.0.0

          - `/12` - 255.240.0.0

          - `/13` - 255.248.0.0

          - `/14` - 255.252.0.0

          - `/15` - 255.254.0.0


          ### Classe B


          - `/16` - 255.255.0.0

          - `/17` - 255.255.128.0

          - `/18` - 255.255.192.0

          - `/19` - 255.255.224.0

          - `/20` - 255.255.240.0

          - `/21` - 255.255.248.0

          - `/22` - 255.255.252.0

          - `/23` - 255.255.254.0


          ### Classe C


          - `/24` - 255.255.255.0

          - `/25` - 255.255.255.128

          - `/26` - 255.255.255.192

          - `/27` - 255.255.255.224

          - `/28` - 255.255.255.240

          - `/29` - 255.255.255.248

          - `/30` - 255.255.255.252

          - `/31` - 255.255.255.254

          - `/32` - 255.255.255.255


          Certifique-se de usar o prefixo CIDR correto conforme a necessidade de
          cálculo de rede.
        parameters: []
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalculadoraIPv4Request'
        responses:
          '200':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: false
                    status: 200
                    result:
                      ipAddress: 192.168.100.1
                      networkAddress: 192.168.100.0
                      usableIPRange: 192.168.100.1 - 192.168.103.254
                      broadcastAddress: 192.168.103.255
                      totalHosts: '1.022'
                      usableHosts: '1.020'
                      subnetMask: 255.255.252.0
                      wildcardMask: 0.0.3.255
                      binarySubnetMask: 11111111.11111111.11111100.00000000
                      ipClass: C
                      cidrNotation: /22
                      ipType: Private Use
                      shortIp: 192.168.100.1/22
                    message: Cálculo realizado com sucesso.
          '400':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: true
                    status: 400
                    result: null
                    message: >-
                      Todos os valores devem ser preenchidos: ipAddress,
                      subnetMask. Por favor, corrija e tente novamente.
          '404':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    Status:
                      error: true
                      status: 404
                      result: null
                      message: >-
                        JSON enviado está incorreto. Por favor, revise o formato
                        e tente novamente.
          '500':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: true
                    status: 500
                    result: null
                    message: >-
                      Prefixo inválido | Por favor, insira um endereço IP válido
                      | Um endereço IP não pode ser maior que 2 elevado à
                      potência de 128, nem ser um número negativo.
    /api/CalculadoraIPv6:
      post:
        tags:
          - Calculadora de IP (IPv6)
        summary: Calculadora de IP (IPv6)
        description: >
          ## Entradas Necessárias


          Os seguintes parâmetros devem ser enviados no corpo da requisição:


          - **ipAddress**: Representa o endereço IP que será analisado.

          - **subnetMask**: Deve ser informado no formato CIDR (ex.: /64).


          # Valores Válidos para o Campo `subnetMask`


          Os valores de prefixo CIDR (`/n`) e suas correspondentes máscaras de
          rede (Network Mask) são de `/1` ... `/128`.


          Certifique-se de usar o prefixo CIDR correto conforme a necessidade de
          cálculo de rede.
        parameters: []
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalculadoraIPv6Request'
        responses:
          '200':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: false
                    status: 200
                    result:
                      ipAddress: 2a02:4780:14:5a20::1
                      ipAddressFull: 2a02:4780:0014:5a20:0000:0000:0000:0001
                      networkAddress: '2a02:4780:14:5a20::'
                      usableIPRange: >-
                        2a02:4780:0014:5a20:0000:0000:0000:0000 -
                        2a02:4780:0014:5a20:ffff:ffff:ffff:ffff
                      totalHosts: 18.446.744.073.709.552.000
                      cidrNotation: /64
                      shortIp: 2a02:4780:14:5a20::1/64
                    message: Cálculo realizado com sucesso.
          '400':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: true
                    status: 400
                    result: null
                    message: >-
                      Todos os valores devem ser preenchidos: ipAddress,
                      subnetMask. Por favor, corrija e tente novamente.
          '404':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    Status:
                      error: true
                      status: 404
                      result: null
                      message: >-
                        JSON enviado está incorreto. Por favor, revise o formato
                        e tente novamente.
          '500':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: true
                    status: 500
                    result: null
                    message: >-
                      Prefixo inválido | Por favor, insira um endereço IP válido
                      | Um endereço IP não pode ser maior que 2 elevado à
                      potência de 128, nem ser um número negativo.
    /api/ConsultaIP:
      post:
        tags:
          - Consulta de IP
        summary: Consulta de IP
        description: >
          ## Entradas Necessárias


          Os seguintes parâmetros devem ser enviados no corpo da requisição:


          - **ip:** Endereço IP que se deseja consultar (opcional). Se vazio,
          retorna informações sobre o IP público atual.
        parameters: []
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsultaIPRequest'
        responses:
          '200':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: false
                    status: 200
                    result:
                      timezone: America/Sao_Paulo
                      organization: AS7162 Universo Online S.A.
                      ip: 200.221.11.100
                      asn: 7162
                      area_code: '0'
                      organization_name: Universo Online S.A.
                      country_code: BR
                      country_code3: BRA
                      continent_code: SA
                      country: Brazil
                      latitude: '-22.8305'
                      longitude: '-43.2192'
                      accuracy: 1000
                    message: Consulta realizada com sucesso.
          '404':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    Status:
                      error: true
                      status: 404
                      result: null
                      message: >-
                        JSON enviado está incorreto. Por favor, revise o formato
                        e tente novamente.
          '500':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: true
                    status: 500
                    result: null
                    message: Endereço IP inválido ou não encontrado.
    /api/GeolocalizacaoIP:
      post:
        tags:
          - Geolocalização de IP
        summary: Geolocalização de IP
        description: |
          ## Entradas Necessárias

          Os seguintes parâmetros devem ser enviados no corpo da requisição:

          - **ip:** Endereço IP que se deseja consultar.
        parameters: []
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeolocalizacaoIPRequest'
        responses:
          '200':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: false
                    status: 200
                    result:
                      query: 2a02:4780:14:5a20::1
                      status: success
                      continent: América do Sul
                      continentCode: SA
                      country: Brasil
                      countryCode: BR
                      region: SP
                      regionName: São Paulo
                      city: São Paulo
                      district: ''
                      zip: '01323'
                      lat: -23.5335
                      lon: -46.6359
                      timezone: America/Sao_Paulo
                      offset: -10800
                      currency: BRL
                      isp: HOSTINGER BR
                      org: Hostinger International Ltd.
                      as: AS47583 Hostinger International Limited
                      asname: AS-HOSTINGER
                      reverse: ''
                      mobile: false
                      proxy: false
                      hosting: true
                    message: Consulta realizada com sucesso.
          '400':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: true
                    status: 400
                    result: null
                    message: >-
                      O ip deve ser preenchido. Por favor, corrija e tente
                      novamente.
          '404':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    Status:
                      error: true
                      status: 404
                      result: null
                      message: >-
                        JSON enviado está incorreto. Por favor, revise o formato
                        e tente novamente.
          '500':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: true
                    status: 500
                    result: null
                    message: Endereço IP inválido ou não encontrado.
    /api/TestePortasRede:
      post:
        tags:
          - Teste de Portas de Rede
        summary: Teste de Portas de Rede
        description: |
          ## Entradas Necessárias

          Os seguintes parâmetros devem ser enviados no corpo da requisição:

          - **host:** Endereço IP ou hostname que se deseja consultar.
          - **port:** Lista de portas a serem testadas.
          - **timeout:** Timeout em milissegundos.
        parameters: []
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestePortasRedeRequest'
        responses:
          '200':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: false
                    status: 200
                    result:
                      host: google.com.br
                      ip: 142.250.184.195
                      testedPorts: 3
                      results:
                        - host: google.com.br
                          ip: 142.250.184.195
                          port: 80
                          status: aberta
                          responseTime: 18ms
                        - host: google.com.br
                          ip: 142.250.184.195
                          port: 443
                          status: aberta
                          responseTime: 27ms
                        - host: google.com.br
                          ip: 142.250.184.195
                          port: 53
                          status: filtrada
                          responseTime: 2239ms
                    message: Teste realizado com sucesso.
          '400':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: true
                    status: 400
                    result: null
                    message: >-
                      Todos os valores devem ser preenchidos: host, port,
                      timeout. Por favor, corrija e tente novamente.
          '404':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    Status:
                      error: true
                      status: 404
                      result: null
                      message: >-
                        JSON enviado está incorreto. Por favor, revise o formato
                        e tente novamente.
          '500':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: true
                    status: 500
                    result: null
                    message: Erro ao realizar o teste
    /api/ConsultaFabricanteMAC:
      post:
        tags:
          - Consulta Fabricante pelo Endereço MAC
        summary: Consulta Fabricante pelo Endereço MAC
        description: |
          ## Entradas Necessárias

          Os seguinte parâmetro deve ser enviado no corpo da requisição:

          - **macaddress:** Endereço MAC que se deseja consultar.
        parameters: []
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsultaFabricanteMACRequest'
        responses:
          '200':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: false
                    status: 200
                    result:
                      startHex: 001A2B000000
                      endHex: 001A2BFFFFFF
                      startDec: '112390569984'
                      endDec: '112407347199'
                      company: Ayecom Technology Co., Ltd.
                      addressL1: No. 25, R&D Road 2, Science-Based Industrial Park
                      addressL2: Hsinchu    300
                      addressL3: ''
                      country: TW
                      type: MA-L
                    message: Consulta realizada com sucesso.
          '400':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: true
                    status: 400
                    result: null
                    message: >-
                      O MAC Address deve ser preenchido. Por favor, corrija e
                      tente novamente.
          '500':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: true
                    status: 500
                    result: null
                    message: MAC Address inválido ou não encontrado.
    /api/CalculadoraDataTransfer:
      post:
        tags:
          - Calculadora de Transferência de Dados
        summary: Calculadora de Transferência de Dados
        description: >
          ## Entradas Necessárias

          Os seguintes parâmetros devem ser fornecidos no corpo da requisição:

          * **tamanho:** Informe o tamanho total do arquivo que será
          transferido. * **unidadeTamanho:** Selecione a unidade de medida
          correspondente ao tamanho do arquivo (por exemplo, MB, GB, TB). *
          **velocidade:** Digite a velocidade disponível para a transferência
          dos dados. * **unidadeVelocidade:** Selecione a unidade de medida da
          velocidade de transferência (por exemplo, Mbps, MB/s, Gbps).

          ## Valores Válidos para o Campo `unidadeTamanho`

          - `B` – Bytes (B)

          - `kB` – Kilobytes (kB)

          - `MB` – Megabytes (MB)

          - `GB` – Gigabytes (GB)

          - `TB` – Terabytes (TB)

          - `PB` – Petabytes (PB)

          - `bit` – Bits (bit)

          - `kbit` – Kilobits (kbit)

          - `Mbit` – Megabits (Mbit)

          - `Gbit` – Gigabits (Gbit)

          - `Tbit` – Terabits (Tbit)

          - `Pbit` – Petabits (Pbit)

          - `KiB` – Kibibytes (KiB)

          - `MiB` – Mebibytes (MiB)

          - `GiB` – Gibibytes (GiB)

          - `TiB` – Tebibytes (TiB)

          - `PiB` – Pebibytes (PiB)

          - `kibit` – Kibibits (kibit)

          - `Mibit` – Mebibits (Mibit)

          - `Gibit` – Gibibits (Gibit)

          - `Tibit` – Tebibits (Tibit)

          - `Pibit` – Pebibits (Pibit)

          ## Valores Válidos para o Campo `unidadeVelocidade`

          - `B` – Bytes por segundo (B/s)

          - `kB` – Kilobytes por segundo (kB/s)

          - `MB` – Megabytes por segundo (MB/s)

          - `GB` – Gigabytes por segundo (GB/s)

          - `TB` – Terabytes por segundo (TB/s)

          - `PB` – Petabytes por segundo (PB/s)

          - `bit` – Bits por segundo (b/s)

          - `kbit` – Kilobits por segundo (kb/s)

          - `Mbit` – Megabits por segundo (Mb/s)

          - `Gbit` – Gigabits por segundo (Gb/s)

          - `Tbit` – Terabits por segundo (Tb/s)

          - `Pbit` – Petabits por segundo (Pb/s)

          - `KiB` – Kibibytes por segundo (KiB/s)

          - `MiB` – Mebibytes por segundo (MiB/s)

          - `GiB` – Gibibytes por segundo (GiB/s)

          - `TiB` – Tebibytes por segundo (TiB/s)

          - `PiB` – Pebibytes por segundo (PiB/s)

          - `kibit` – Kibibits por segundo (kib/s)

          - `Mibit` – Mebibits por segundo (Mib/s)

          - `Gibit` – Gibibits por segundo (Gib/s)

          - `Tibit` – Tebibits por segundo (Tib/s)

          - `Pibit` – Pebibits por segundo (Pib/s)
        parameters: []
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalculadoraDataTransferRequest'
        responses:
          '200':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: false
                    status: 200
                    result:
                      tempo_estimado: '01:25:20'
                    message: Calculo realizado com sucesso.
          '400':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: true
                    status: 400
                    result: null
                    message: >-
                      O MAC Address deve ser preenchido. Por favor, corrija e
                      tente novamente.
          '500':
            description: ''
            content:
              application/json:
                schema:
                  type: object
                  example:
                    error: true
                    status: 500
                    result: null
                    message: MAC Address inválido ou não encontrado.
